-- ============================================================
--  진동시험기 예약 - Supabase 스키마
--  Supabase 대시보드 > SQL Editor 에 붙여넣고 [Run] 실행하세요.
--  (이 앱은 로그인 없는 공용 예약앱이므로 anon 키로 접근하고
--   RLS 정책을 공개로 열어줍니다. 사내 소규모 사용 전제.)
-- ============================================================

-- 1) 예약 테이블 -------------------------------------------------
create table if not exists public.reservations (
  id          bigint generated by default as identity primary key,
  machine     text        not null default '진동시험기 1호',  -- 장비명
  date        date        not null,                            -- 예약 날짜 (YYYY-MM-DD)
  hour        int         not null check (hour between 8 and 19), -- 시각(8=08:00~09:00)
  name        text        not null,                            -- 예약자 (필수)
  dept        text,                                            -- 부서/연락처 (선택)
  memo        text,                                            -- 메모 (선택)
  email       text,                                            -- 이메일 (선택)
  created_at  timestamptz not null default now()               -- 생성 시각
);

-- 2) 중복예약 원천차단: 같은 장비·날짜·시각은 단 1건 ----------------
--    (예약 1건 = 1시간 = 1행)
create unique index if not exists reservations_unique_slot
  on public.reservations (machine, date, hour);

-- 조회 성능용 인덱스 (장비+날짜로 자주 조회)
create index if not exists reservations_machine_date_idx
  on public.reservations (machine, date);

-- 3) RLS(행 수준 보안) 활성화 ------------------------------------
alter table public.reservations enable row level security;

-- 4) 공개 정책: anon(익명) 사용자에게 조회/등록/삭제 허용 ----------
--    ※ 로그인 없는 전체공개 공용장비 앱이라 의도적으로 열어둡니다.
--      민감 데이터가 아니고 사내에서만 URL을 공유하는 전제입니다.
drop policy if exists "public_select" on public.reservations;
create policy "public_select" on public.reservations
  for select to anon using (true);

drop policy if exists "public_insert" on public.reservations;
create policy "public_insert" on public.reservations
  for insert to anon with check (true);

drop policy if exists "public_delete" on public.reservations;
create policy "public_delete" on public.reservations
  for delete to anon using (true);

-- (update 는 이 앱에서 쓰지 않으므로 정책을 만들지 않습니다.
--  → 확장 가능: 예약 수정 기능이 필요하면 for update 정책 추가)

-- 끝. 이제 index.html 상단에 Project URL / anon key 를 채우면 동작합니다.
